name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build
  #     working-directory: ./convenience-middleware/
  #     run: cargo build --verbose
  #   - name: Run tests
  #     working-directory: ./convenience-middleware/
  #     run: cargo test --verbose

  riscv:
    name: RiscV Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenSSL
        run: sudo apt-get install openssl libssl-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: riscv64gc-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target riscv64gc-unknown-linux-gnu --verbose -p cartesi-drand

