name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./convenience-middleware/
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./convenience-middleware/
      run: cargo test --verbose

  riscv:
    name: Windows Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: riscv64gc-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          working-directory: ./convenience-middleware/
          command: build
          args: --release --target riscv64gc-unknown-linux-gnu